# Generated by Django 5.2 on 2026-04-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
